# Generated by Django 4.1.5 on 2023-08-28 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('listItems', models.CharField(max_length=2500)),
            ],
        ),
    ]
