# Generated by Django 4.1.5 on 2023-08-28 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoApp', '0002_contenttable'),
    ]

    operations = [
        migrations.CreateModel(
            name='blogTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogHeading', models.CharField(max_length=255)),
                ('blogAuthor', models.CharField(max_length=255)),
                ('summaryDesc', models.CharField(max_length=255)),
            ],
        ),
    ]
