# Generated by Django 4.1.5 on 2023-08-28 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoApp', '0003_blogtable'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogtable',
            name='imgDesc',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
